name: EC2-PRODUCTION-BACKEND

# Trigger deployment only on push to the development branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy and Setup on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set permissions on the remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_EC2_SSH_KEY }}
          script: |
            sudo chown -R ${{ secrets.PROD_USERNAME }}:${{ secrets.PROD_USERNAME }} ${{ secrets.PROD_TARGET_DIR }}
            sudo chmod -R 755 ${{ secrets.PROD_TARGET_DIR }}

      - name: Deploy files to the server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PROD_EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.PROD_HOST }}
          REMOTE_USER: ${{ secrets.PROD_USERNAME }}
          TARGET: ${{ secrets.PROD_TARGET_DIR }}

      - name: Setup and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.PROD_TARGET_DIR }}
            npm install
            pm2 restart all
